trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solutionPath: 'src/api/MyFoodTracker/MyFoodTracker.Api.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: "BuildApi"
        steps:
        - task: DotNetCoreCLI@2
          displayName: dotnet Publish
          inputs:
            command: publish
            publishWebProjects: false
            projects: "$(solutionPath)"
            arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
            zipAfterPublish: false
        - task: ArchiveFiles@2
          displayName: Zip Api
          inputs:
            rootFolderOrFile: "$(Build.ArtifactStagingDirectory)/api"
            includeRootFolder: false
            archiveType: "zip"
            archiveFile: "$(Build.ArtifactStagingDirectory)/out/appts-alpha-api-$(Build.BuildId).zip"
            replaceExistingArchive: true
        - task: PublishBuildArtifacts@1
          displayName: "Publish Artifact"
          inputs:
            PathtoPublish: "$(Build.ArtifactStagingDirectory)/out"
            ArtifactName: "drop_api"
            publishLocation: "Container"            